/* Generated by tools/build-last-update.py. Do not hand-edit.
   Each stamp moves only when that pack's content fingerprint changes.
   The fingerprint covers the pack's draft-v1-linked tree plus _shared,
   excluding this file, with every ?v= query stripped first.
   Re-run the script and commit this file plus the last-update.js?v=
   stamps it writes. */
(function () {
  var STAMPS = {
    "cf2018": {
      "text": "Last update · 2026-10-10 18:36 HKT",
      "iso": "2026-10-10T18:36:00+08:00",
      "fingerprint": "9d71c4ceace7a2ae012d4134ebb6533c0da7b6c5415928337f3a7a25624e3401"
    },
    "ias16": {
      "text": "Last update · 2026-10-11 03:18 HKT",
      "iso": "2026-10-11T03:18:00+08:00",
      "fingerprint": "78df787a55701897b0a59f7edbe52b36a1a1ab365d3afb938f6e540faf93d242"
    },
    "ias2": {
      "text": "Last update · 2026-10-10 18:36 HKT",
      "iso": "2026-10-10T18:36:00+08:00",
      "fingerprint": "eaf2f8c43d4e57a108ada34132e10ef8369b666fc52833fe4419c82bacfd0edd"
    },
    "ifrs18": {
      "text": "Last update · 2026-10-10 18:36 HKT",
      "iso": "2026-10-10T18:36:00+08:00",
      "fingerprint": "e608f4ec9a3baa2ff1f0950d49884152e3392c2dcd19f5da9da9f48bb23d9182"
    }
  };

  var PACK_PATHS = [
    ["/cf-2018/", "cf2018"],
    ["/ias-16/", "ias16"],
    ["/ias-2/", "ias2"],
    ["/ifrs-18/", "ifrs18"]
  ];

  function packId() {
    var body = document.body;
    var fromBody = body && body.getAttribute("data-pack");
    if (fromBody && STAMPS[fromBody]) return fromBody;
    var path = location.pathname || "";
    var i;
    for (i = 0; i < PACK_PATHS.length; i++) {
      if (path.indexOf(PACK_PATHS[i][0]) !== -1) return PACK_PATHS[i][1];
    }
    return "";
  }

  function formatStamp(stamp) {
    var match = /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(stamp.iso || "");
    if (match) return "Last update \u00b7 " + match[1] + " " + match[2] + " HKT";
    return stamp.text || "";
  }

  function mount() {
    var stamp = STAMPS[packId()];
    if (!stamp) return false;
    var el = document.querySelector("span.chrome-last-update");
    if (!el) {
      var host = document.querySelector(".chrome-title-cluster") || document.querySelector(".chrome-bar-title");
      if (!host) return false;
      el = document.createElement("span");
      el.className = "chrome-last-update";
      host.appendChild(el);
    }
    if (el.getAttribute("data-last-update-ready") === "true") return true;
    el.textContent = formatStamp(stamp);
    el.setAttribute("data-last-update", stamp.iso);
    el.removeAttribute("title");
    el.setAttribute("data-last-update-ready", "true");
    return true;
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mount);
  } else {
    mount();
  }
})();
