/* Generated by tools/build-last-update.py. Do not hand-edit.
   Each stamp moves only when that pack's content fingerprint changes.
   The fingerprint covers the pack's draft-v1-linked tree plus _shared,
   excluding this file, with every ?v= query stripped first.
   Re-run the script and commit this file plus the last-update.js?v=
   stamps it writes. */
(function () {
  var STAMPS = {
    "cf2018": {
      "text": "Last update · 2026-10-10 01:17 HKT",
      "iso": "2026-10-10T01:17:00+08:00",
      "fingerprint": "c7e68361536ff0af1e7d5417c863e426d479f1d0a32f6fd97f2319a691268c2d"
    },
    "ias16": {
      "text": "Last update · 2026-10-10 01:17 HKT",
      "iso": "2026-10-10T01:17:00+08:00",
      "fingerprint": "8b407b1bcd5a23b74243024693d737ecb8941b48a0aa05f8a7afc17ab9f0bba8"
    },
    "ias2": {
      "text": "Last update · 2026-10-10 01:17 HKT",
      "iso": "2026-10-10T01:17:00+08:00",
      "fingerprint": "ad4fac05d9076dbb16e2eb3b241ead3f136cc89180a7fba53501a40b433a5755"
    },
    "ifrs18": {
      "text": "Last update · 2026-10-10 01:17 HKT",
      "iso": "2026-10-10T01:17:00+08:00",
      "fingerprint": "a32058e91a4f6df312f1d8b109728625262049911a71fd267322ad6aab2145cc"
    }
  };

  var PACK_PATHS = [
    ["/cf-2018/", "cf2018"],
    ["/ias-16/", "ias16"],
    ["/ias-2/", "ias2"],
    ["/ifrs-18/", "ifrs18"]
  ];

  function packId() {
    var body = document.body;
    var fromBody = body && body.getAttribute("data-pack");
    if (fromBody && STAMPS[fromBody]) return fromBody;
    var path = location.pathname || "";
    var i;
    for (i = 0; i < PACK_PATHS.length; i++) {
      if (path.indexOf(PACK_PATHS[i][0]) !== -1) return PACK_PATHS[i][1];
    }
    return "";
  }

  function formatStamp(stamp) {
    var match = /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(stamp.iso || "");
    if (match) return "Last update \u00b7 " + match[1] + " " + match[2] + " HKT";
    return stamp.text || "";
  }

  function mount() {
    var stamp = STAMPS[packId()];
    if (!stamp) return false;
    var el = document.querySelector("span.chrome-last-update");
    if (!el) {
      var host = document.querySelector(".chrome-title-cluster") || document.querySelector(".chrome-bar-title");
      if (!host) return false;
      el = document.createElement("span");
      el.className = "chrome-last-update";
      host.appendChild(el);
    }
    if (el.getAttribute("data-last-update-ready") === "true") return true;
    el.textContent = formatStamp(stamp);
    el.setAttribute("data-last-update", stamp.iso);
    el.removeAttribute("title");
    el.setAttribute("data-last-update-ready", "true");
    return true;
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mount);
  } else {
    mount();
  }
})();
