/* Generated by tools/build-last-update.py. Do not hand-edit.
   Each stamp moves only when that pack's content fingerprint changes.
   The fingerprint covers the pack's draft-v1-linked tree plus _shared,
   excluding this file, with every ?v= query stripped first.
   Re-run the script and commit this file plus the last-update.js?v=
   stamps it writes. */
(function () {
  var STAMPS = {
    "cf2018": {
      "text": "Last update · 2026-10-07 21:38 HKT",
      "iso": "2026-10-07T21:38:00+08:00",
      "fingerprint": "2b85d8d674fceffdfef50765222a179007d5adbb2bfd15ab20220e5bc96cb85c"
    },
    "ias16": {
      "text": "Last update · 2026-10-08 12:03 HKT",
      "iso": "2026-10-08T12:03:00+08:00",
      "fingerprint": "50f34aba05d5b9246937709b5f769c3f01b02f9fdd3cde4c773412b0afc951aa"
    },
    "ias2": {
      "text": "Last update · 2026-10-07 21:38 HKT",
      "iso": "2026-10-07T21:38:00+08:00",
      "fingerprint": "d221ff1618c4d825f864a91e937a2122c5084b497b7407ab83d9b19050304505"
    },
    "ifrs18": {
      "text": "Last update · 2026-10-07 21:38 HKT",
      "iso": "2026-10-07T21:38:00+08:00",
      "fingerprint": "e42a867d3eb928146574eacabd34b3e1fc3ca4570f9b2edbb6d03b6dbbc6f86c"
    }
  };

  var PACK_PATHS = [
    ["/cf-2018/", "cf2018"],
    ["/ias-16/", "ias16"],
    ["/ias-2/", "ias2"],
    ["/ifrs-18/", "ifrs18"]
  ];

  function packId() {
    var body = document.body;
    var fromBody = body && body.getAttribute("data-pack");
    if (fromBody && STAMPS[fromBody]) return fromBody;
    var path = location.pathname || "";
    var i;
    for (i = 0; i < PACK_PATHS.length; i++) {
      if (path.indexOf(PACK_PATHS[i][0]) !== -1) return PACK_PATHS[i][1];
    }
    return "";
  }

  function formatStamp(stamp) {
    var match = /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(stamp.iso || "");
    if (match) return "Last update \u00b7 " + match[1] + " " + match[2] + " HKT";
    return stamp.text || "";
  }

  function mount() {
    var stamp = STAMPS[packId()];
    if (!stamp) return false;
    var el = document.querySelector("span.chrome-last-update");
    if (!el) {
      var host = document.querySelector(".chrome-title-cluster") || document.querySelector(".chrome-bar-title");
      if (!host) return false;
      el = document.createElement("span");
      el.className = "chrome-last-update";
      host.appendChild(el);
    }
    if (el.getAttribute("data-last-update-ready") === "true") return true;
    el.textContent = formatStamp(stamp);
    el.setAttribute("data-last-update", stamp.iso);
    el.removeAttribute("title");
    el.setAttribute("data-last-update-ready", "true");
    return true;
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", mount);
  } else {
    mount();
  }
})();
